// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIRenameFiles(arg1, arg2) {
  return window['go']['main']['App']['AIRenameFiles'](arg1, arg2);
}

export function GenerateAINames(arg1, arg2) {
  return window['go']['main']['App']['GenerateAINames'](arg1, arg2);
}

export function GetAIModels(arg1) {
  return window['go']['main']['App']['GetAIModels'](arg1);
}

export function GetFilesFromFileInfos(arg1) {
  return window['go']['main']['App']['GetFilesFromFileInfos'](arg1);
}

export function GetFilesFromPaths(arg1, arg2) {
  return window['go']['main']['App']['GetFilesFromPaths'](arg1, arg2);
}

export function LoadAIConfig() {
  return window['go']['main']['App']['LoadAIConfig']();
}

export function LoadPromptTemplates() {
  return window['go']['main']['App']['LoadPromptTemplates']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RenameFiles(arg1, arg2) {
  return window['go']['main']['App']['RenameFiles'](arg1, arg2);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SavePromptTemplates(arg1) {
  return window['go']['main']['App']['SavePromptTemplates'](arg1);
}

export function SetAIAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAIAPIKey'](arg1, arg2);
}

export function SetAIModel(arg1) {
  return window['go']['main']['App']['SetAIModel'](arg1);
}
