// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AIRenameFiles(arg1:Array<main.FileInfo>,arg2:Array<string>):Promise<Array<string>>;

export function GenerateAINames(arg1:Array<main.FileInfo>,arg2:string):Promise<Array<string>>;

export function GetAIModels(arg1:string):Promise<Array<main.ModelInfo>>;

export function GetFilesFromFileInfos(arg1:Array<main.FileInfo>):Promise<Array<main.FileInfo>>;

export function GetFilesFromPaths(arg1:Array<string>,arg2:boolean):Promise<Array<main.FileInfo>>;

export function LoadAIConfig():Promise<main.AIConfig>;

export function LoadPromptTemplates():Promise<main.PromptTemplates>;

export function OpenFileDialog():Promise<Array<string>>;

export function OpenFolderDialog():Promise<Array<string>>;

export function RenameFiles(arg1:Array<main.FileInfo>,arg2:main.RenameRule):Promise<Array<string>>;

export function SaveAIConfig(arg1:main.AIConfig):Promise<void>;

export function SavePromptTemplates(arg1:main.PromptTemplates):Promise<void>;

export function SetAIAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetAIModel(arg1:string):Promise<void>;
